//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysGestor.RESOURCE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysGestor.RESOURCE.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao excluir dados.
        /// </summary>
        public static string DeleteDataErros {
            get {
                return ResourceManager.GetString("DeleteDataErros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo tipo cliente é obrigatório.
        /// </summary>
        public static string EmptyCustomerType {
            get {
                return ResourceManager.GetString("EmptyCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição não pode ser vazio.
        /// </summary>
        public static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo e-mail não pode ser vazio.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome não pode ser vazio.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não informada.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo telefone não pode ser vazio.
        /// </summary>
        public static string EmptyPhone {
            get {
                return ResourceManager.GetString("EmptyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não informado.
        /// </summary>
        public static string EmptyUser {
            get {
                return ResourceManager.GetString("EmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um valor igual ao que você está tentando inserir.
        /// </summary>
        public static string EqualsValue {
            get {
                return ResourceManager.GetString("EqualsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao inserir dados.
        /// </summary>
        public static string InsertDataErrors {
            get {
                return ResourceManager.GetString("InsertDataErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de documento inválido ou não foi informado.
        /// </summary>
        public static string InvalidDocumento {
            get {
                return ResourceManager.GetString("InvalidDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login vazio ou inválido.
        /// </summary>
        public static string InvalidEmptyLogin {
            get {
                return ResourceManager.GetString("InvalidEmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha vazio ou inválida.
        /// </summary>
        public static string InvalidEmptyPassword {
            get {
                return ResourceManager.GetString("InvalidEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro não pode ser vazio ou null.
        /// </summary>
        public static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido ou não foi informado.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor não pode ser null.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade não informada.
        /// </summary>
        public static string NullQtd {
            get {
                return ResourceManager.GetString("NullQtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor retornado é null.
        /// </summary>
        public static string NullReturn {
            get {
                return ResourceManager.GetString("NullReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar dados.
        /// </summary>
        public static string SelectDataErrors {
            get {
                return ResourceManager.GetString("SelectDataErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao alterar dados.
        /// </summary>
        public static string UpdateDataErrors {
            get {
                return ResourceManager.GetString("UpdateDataErrors", resourceCulture);
            }
        }
    }
}
